name: android_process_state
description: Android process foreground-state bridge for kaoyan_review.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.13.4

flutter:
  plugin:
    platforms:
      android:
        package: com.wly112488.android_process_state
        pluginClass: AndroidProcessStatePlugin

dependencies:
  flutter:
    sdk: flutter
